services:
  api:
    build: .
    depends_on:
      database:
        condition: service_healthy
    networks:
      - application
    ports:
      - "8080:8080"
  database:
    command: --require_secure_transport=OFF
    environment:
      MYSQL_DATABASE: taskmaster
      MYSQL_USER: application
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 30s
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
    image: mysql:latest
    networks:
      - application
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - database_volume:/var/lib/mysql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
networks:
  application:
    driver: bridge
volumes:
  database_volume:
    driver: local
